name: ld-multiancestry

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - pyyaml
  - pytest
  - pytorch
  - pip
  - pip:
      - cyvcf2
